# frozen_string_literal: true

source "https://rubygems.org"

# pact-ruby-standalone
gem "pact", "~> 1.64"
gem "pact_broker-client", "~> 1.75", ">= 1.75.1"
gem "pact-mock_service", "~> 3.11", ">= 3.11.2" # cant upgrade until pact broker supports rack 3
gem "pact-provider-verifier", "~> 1.38"

# pact_broker
gem "nokogiri", "~> 1.16", ">= 1.16.2"
gem "mysql2", "~> 0.5.6"
gem "pact_broker", "~> 2.111.0", ">= 2.111.0"
gem "pg", "~> 1.5", ">= 1.5.5"
gem "puma", "~> 6.4", ">= 6.4.2"
gem "sequel", "~> 5.77"
gem "sqlite3", "~> 1.7", ">= 1.7.2", force_ruby_platform: true
gem "thin"
