# frozen_string_literal: true

source "https://rubygems.org"

# pact-ruby-standalone
gem "pact"
gem "pact_broker-client"
gem "pact-mock_service"
gem "pact-provider-verifier"

# pact_broker
gem "nokogiri"
gem "mysql2"
gem "pact_broker"
gem "pg"
gem "puma"
gem "sequel"
gem "sqlite3"
gem "thin"
