name: Package app

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [
          macos-14, 
          macos-13, 
          # ubuntu-20.04, 
          # windows-latest
          ]

    steps:
      - uses: actions/checkout@v4
        
      - uses: actions/cache@v4
        id: cache-unix
        with:
          path: ~/.tebako/
          key: ${{ matrix.os }}
        if: runner.os != 'Windows'

        
      - uses: actions/cache@v4
        id: cache-win
        with:
          path: D:/a/_temp/msys64/home/runneradmin/.tebako/
          key: ${{ matrix.os }}
        if: runner.os == 'Windows'

      - name: Setup ruby
        uses: ruby/setup-ruby@master
        with:
            ruby-version: '3.2.5'
        if: runner.os != 'Windows'
            
      - run: |
            sudo apt install -y gcc-10 g++-10
            sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10
            sudo apt-get remove --purge --auto-remove cmake
            sudo apt-get update
            sudo apt-get install -y software-properties-common lsb-release curl
            sudo apt-get clean all
            curl https://apt.kitware.com/kitware-archive.sh | sudo bash
            sudo apt-get -y install git curl build-essential pkg-config bison flex autoconf  \
            binutils-dev libevent-dev acl-dev libfmt-dev libjemalloc-dev libiberty-dev    \
            libdouble-conversion-dev liblz4-dev liblzma-dev libssl-dev libunwind-dev      \
            libboost-filesystem-dev libboost-program-options-dev libboost-system-dev      \
            libboost-iostreams-dev  libboost-date-time-dev libboost-context-dev           \
            libboost-regex-dev libboost-thread-dev libbrotli-dev libdwarf-dev libelf-dev  \
            libgoogle-glog-dev libffi-dev libgdbm-dev libyaml-dev libncurses-dev          \
            libreadline-dev libncurses-dev libreadline-dev ruby-dev ruby-bundler          \
            libutfcpp-dev
        if: runner.os == 'Linux'
        name: install ${{runner.os}} deps

      - name: Select XCode
        if: runner.os == 'MacOS'
        uses: maxim-lobanov/setup-xcode@v1
        with:
            xcode-version: 14.3.1
      - if: runner.os == 'MacOS'
        name: install ${{runner.os}} deps
        run: |
          brew install bison flex binutils libffi double-conversion boost jemalloc fmt glog gnu-sed bash zlib ncurses
          echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH

      - if: runner.os == 'Windows'
        name: install ${{runner.os}} deps
        uses: msys2/setup-msys2@v2
        with:
          msystem: ucrt64
          path-type: minimal
          update: true
          install: >-
            git
            tar
            bison
            flex
          pacboy: >-
            cmake:p
            boost:p
            diffutils:p
            libevent:p
            double-conversion:p
            fmt:p
            glog:p
            dlfcn:p
            ninja:p
            gtest:p
            autotools:p
            ncurses:p
            ruby:p
            toolchain:p
            openssl:p
            make:p
            libyaml:p
            libxslt:p
            postgresql:p
            libmariadbclient:p
      - name: set windows env vars
        if: runner.os == 'Windows'
        run: |
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV
          echo "TOOLCHAIN=msys" >> $GITHUB_ENV
          echo "MSYSTEM=UCRT64" >> $GITHUB_ENV
      # - name: Install pacman packages
      #   if: runner.os == 'Windows'
      #   shell: msys2 {0}
      #   run: |
      #     pacman -Syu --needed --noconfirm git tar bison flex pactoys
      #     pacboy sync --needed --noconfirm cmake:p boost:p diffutils:p  \
      #       libevent:p double-conversion:p fmt:p glog:p dlfcn:p ninja:p \
      #       gtest:p autotools:p ncurses:p ruby:p toolchain:p openssl:p  \
      #       make:p libyaml:p libxslt:p
      
      - run: gem install tebako
        name: install packager
        shell: msys2 {0}
        if: runner.os == 'Windows'

      - run: gem install tebako
        name: install packager
        if: runner.os != 'Windows'

      - run: tebako setup
        name: setup press
        shell: msys2 {0}
        if: runner.os == 'Windows' && steps.cache-win.outputs.cache-hit != 'true'

      - run: tebako setup
        name: setup press
        if: runner.os != 'Windows' && steps.cache-unix.outputs.cache-hit != 'true'


        # mysql2 workaround for windows - https://github.com/brianmario/mysql2/issues/1265#issuecomment-1200407838
      # - run: |
      #     touch /ucrt64/bin/libmysql.lib
      #     cp /ucrt64/bin/libmariadb.dll /ucrt64/bin/libmysql.dll
      #     gem install mysql2 -- --with-mysql-lib="/ucrt64/bin" --with-mysql-include="/ucrt64/include/mariadb"
      #     tebako press --root=app --entry-point=app --output=pact-cli-${{runner.OS}}-${{runner.arch}}
      #   name: press app
      #   shell: msys2 {0}
      #   if: runner.os == 'Windows'


      - run: tebako press --root=app --entry-point=app --output=pact-cli-${{runner.OS}}-${{runner.arch}}
        name: press app
        if: runner.os != 'Windows'

      - uses: actions/upload-artifact@v4
        with:
          name: pact-cli-${{runner.OS}}-${{runner.arch}}
          path: pact-cli-${{runner.OS}}-${{runner.arch}}


  # docker:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       shell: bash
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       docker-os: [ubuntu-20.04,alpine-3.17]

  #   steps:
  #     - uses: actions/checkout@v4
        
  #     - name: pull image
  #       run: docker pull ghcr.io/tamatebako/tebako-${{ matrix.docker-os }}:latest
  #     - name: Docker dependencies
  #       id: docker_commands
  #       shell: bash
  #       run: |
  #         if [[ ${{ matrix.docker-os }} == *"alpine"* ]]; then
  #           echo "deps=apk del clang && apk add postgresql-dev mariadb-dev && " >> "$GITHUB_OUTPUT"
  #         else
  #           echo "deps=apt-get update -y && apt-get install -y libpq-dev libmariadb-dev && " >> "$GITHUB_OUTPUT"
  #         fi
  #     - name: run image
  #       run: | 
  #         docker run -v $PWD:/mnt/w \
  #           -t ghcr.io/tamatebako/tebako-${{ matrix.docker-os }}:latest \
  #           /bin/sh -c '${{ steps.docker_commands.outputs.deps }}tebako press --root=/mnt/w/app --entry-point=app --output=/mnt/w/pact-cli-${{ matrix.docker-os }}-${{ runner.arch }}'

  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: pact-cli-${{ matrix.docker-os }}-${{ runner.arch }}
  #         path: pact-cli-${{ matrix.docker-os }}-${{ runner.arch }}
