# This is a basic workflow to help you get started with Actions

name: pact cli

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019,macos-latest,ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: pactflow/actions@test_cli_action
