name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  STABLE_PYTHON_VERSION: "3.11"
  PYTEST_ADDOPTS: --color=yes

jobs:
  test:
    name: Example

    runs-on: ubuntu-latest
    services:
      nginx:
        image: nginx
        ports:
          - "8080:80"
        options: >-
          --health-cmd "curl -sSf http://localhost:80"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      broker:
        image: pactfoundation/pact-broker:latest-multi
        ports:
          - "9292:9292"
        env:
          # Basic auth credentials for the Broker
          PACT_BROKER_ALLOW_PUBLIC_READ: "true"
          PACT_BROKER_BASIC_AUTH_USERNAME: pactbroker
          PACT_BROKER_BASIC_AUTH_PASSWORD: pactbroker
          # Database
          PACT_BROKER_DATABASE_URL: sqlite:////tmp/pact_broker.sqlite
        # options: >-
        #   --health-cmd "curl -sSf http://localhost:9292/diagnostic/status/heartbeat"
        #   --health-retries 3

    steps:
      - name: Ports
        run: |
          sudo lsof -i -nP | grep LISTEN
      - name: Wait for the broker to start
        run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/$WAIT_FOR_VERSION/wait-for | sh -s -- http://localhost:9292/diagnostic/status/heartbeat -t 30 -- echo "Database is up"
        env:
          WAIT_FOR_VERSION: 4df3f9262d84cab0039c07bf861045fbb3c20ab7 # v2.2.3
      - name: Check nginx is line
        run: |
          curl -sSf http://localhost:8080
      - name: Check broker is live
        run: |
          curl -sSf http://0.0.0.0:9292/diagnostic/status/heartbeat \
          || curl -sSf http://0.0.0.0:9292
      - name: Check broker is live localhost
        run: |
          curl -sSf http://localhost:9292/diagnostic/status/heartbeat \
          || curl -sSf http://localhost:9292